services:
  - type: web
    name: jarawork
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: CIRCLE_DEVELOPER_CONTROLLED_API_KEY
        sync: false
      - key: CIRCLE_ENTITY_SECRET
        sync: false
      - key: VITE_CONTRACT_ADDRESS
        sync: false
      - key: VITE_AGENT_WALLET_ID
        sync: false
      - key: VITE_AGENT_WALLET_SET_ID
        sync: false
      - key: VITE_AGENT_WALLET_ADDRESS
        sync: false
